development:
  adapter: postgresql
  encoding: unicode
  database: sampleapp_db
  host: localhost
  pool: 5
  username: postgres
  password: 123
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: d8au9j6ocvojhv
  pool: 5
  username: cksejlxpnnsayd
  password: s1SZRisAMt1lFGp0LxGb85WYZ5
  host: ec2-54-197-241-95.compute-1.amazonaws.com
  port: 5432

test:
    adapter: postgresql
    encoding: unicode
    database: sampleapp_db
    host: localhost
    pool: 5
    username: postgres
    password: 123
    port: 5432

