# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77c88512a47277450e161240f81fb27d4ce3e2da0403520d4a3450c9ef9c97d2c2671c9995533a927fba497112ae65b8a528edfc1d55ef33d31389f0a0298c5

test:
  secret_key_base: 129c28aecd085cd91eb0088d755ba5fc3699079577bbaf5b53ab596e9be163fd4595785dc74ceaf82ac8fb08acad59149c5827863416244f47271af77e1391e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
